### ISSUE TITLE
能写个NAS的docker教程吗?

### ISSUE THREAD

**Issue by chaoji2020** [FleyX/bookmark#6]
你好,首先感谢作者开源.
目前使用上遇到一些问题.
按照这个教程第一步root运行init.sh,报这些错误,

![init](https://user-images.githubusercontent.com/72678441/98078124-6dc88c80-1eac-11eb-9388-e5588acf688d.png)

**Comment by chaoji2020** [comment]
修改了真实地址


![init1](https://user-images.githubusercontent.com/72678441/98078304-cc8e0600-1eac-11eb-9e2b-b9b9a461efbd.png)

**Comment by chaoji2020** [comment]
> 你好,首先感谢作者开源.
   目前使用上遇到一些问题.
> 按照这个教程第一步root运行init.sh,报这些错误,
> 
> ![init](https://user-images.githubusercontent.com/72678441/98078124-6dc88c80-1eac-11eb-9388-e5588acf688d.png)

**Comment by FleyX** [comment]
是把整个仓库clone后，然后进入bookMarkDocker目录执行init.sh脚本的吗？

**Comment by chaoji2020** [comment]
pull下来容器没运行 然后执行init.sh脚本&nbsp;不确定是不是NAS的docker是不是跟其他linux系统的不一样&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "FleyX"<notifications@github.com&gt;; 
发送时间: 2020年11月4日(星期三) 下午2:56
收件人: "FleyX/bookmark"<bookmark@noreply.github.com&gt;; 
抄送: "573257382"<573257382@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [FleyX/bookmark] 能写个NAS的docker教程吗? (#6)





 
是把整个仓库clone后，然后进入bookMarkDocker目录执行init.sh脚本的吗？

**Comment by FleyX** [comment]
这个需要部署在linux环境中，不能在某个容器中运行
在linux环境中先把仓库clone下来
然后cd到bookMarkDocker目录中执行init.sh脚本
最后执行docker-compose up -d启动所有服务（需要先安装docker-compose软件）

需要有一定的linux使用能力

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: chaoji2020<mailto:notifications@github.com>
发送时间: 2020年11月4日 15:05
收件人: FleyX/bookmark<mailto:bookmark@noreply.github.com>
抄送: FleyX<mailto:fleyx20@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [FleyX/bookmark] 能写个NAS的docker教程吗? (#6)

pull下来容器没运行 然后执行init.sh脚本&nbsp;不确定是不是NAS的docker是不是跟其他linux系统的不一样&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "FleyX"<notifications@github.com&gt;;
发送时间: 2020年11月4日(星期三) 下午2:56
收件人: "FleyX/bookmark"<bookmark@noreply.github.com&gt;;
抄送: "573257382"<573257382@qq.com&gt;; "Author"<author@noreply.github.com&gt;;
主题: Re: [FleyX/bookmark] 能写个NAS的docker教程吗? (#6)






是把整个仓库clone后，然后进入bookMarkDocker目录执行init.sh脚本的吗？

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

―

**Comment by chaoji2020** [comment]
原来如此. 我误会了. 群晖不知道支不支持docker-compose 如果能集成到单容器就完美了

**Comment by FleyX** [comment]
哈哈，未来可能会支持单容器部署，现在比较忙，没时间继续搞这个。
那我关闭这个issue了。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: chaoji2020<mailto:notifications@github.com>
发送时间: 2020年11月4日 15:18
收件人: FleyX/bookmark<mailto:bookmark@noreply.github.com>
抄送: FleyX<mailto:fleyx20@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [FleyX/bookmark] 能写个NAS的docker教程吗? (#6)


原来如此. 我误会了. 群晖不知道支不支持docker-compose 如果能集成到单容器就完美了

―
